### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by Mu7ammadAbed** [GSG-G9/dentoro#7]

**Comment by Alaalser** [comment]
## Schema Tables
![image](https://user-images.githubusercontent.com/62717875/112476250-6120d400-8d7a-11eb-8879-604af0ac4888.png)




## Schema Info
- ### patients
| Column            | Type                    | Modifiers               |
| ----------------- |:----------------------- |:----------------------- |
  id | SERIAL | primary key
  first_name|  VARCHAR(100) | not null
  last_name|  VARCHAR(100) | not null
  email|  VARCHAR(100) | not null
  birthday | DATE | not null
  phone| VARCHAR(100) | not null
  

- ### appointnets
  
| Column            | Type                    | Modifiers               |
| ----------------- |:----------------------- |:----------------------- |
  id | SERIAL | primary key
  patient_id | INTEGER |  REFERENCES patients(id)
  appointnet_data| DATE | not null
  appointnet_data| TIME | not null
  is_done| Boolean | not null
  complaines | TEXT | not null
  chronic_diseases | TEXT | not null

  
- ### history

| Column            | Type                    | Modifiers               |
| ----------------- |:----------------------- |:----------------------- |
  id | SERIAL | primary key
  patient_id | INTEGER |  REFERENCES patients(id)
  description| TEXT | not null
  price| FLOAT | not null
  payment| FLOAT | not null
  appointnet_data| DATE | not null


- ### users

| Column            | Type                    | Modifiers               |
| ----------------- |:----------------------- |:----------------------- |
  id | SERIAL | primary key
  email | VARCHAR(250) | not null
  password | VARCHAR(250) | not null
